credentials:
  usernames:
    admin:
      email: admin@example.com
      name: 管理者
      password: $2b$12$Q/cWE..1CQQPNJrN9clZwO5eDPfeBXheXKfco65k7Ar6B5m.YPUdG
cookie:
  expiry_days: 30
  key: financial_auth_key
  name: financial_auth
preauthorized:
  emails:
    - admin@example.com

